### ISSUE TITLE
Kernel size calculation & folding workflow in your code

### ISSUE THREAD

**Issue by xingpz2008** [LayerFolding/Layer-Folding#3]
Hi,

I have read your paper and code recently, while the result and idea in tis paper seems amazing.
However, due to inefficiency in knowledge of convolution networks, I was confused when I saw the follow code:

 

>        if stride == 1:
>            self.new_conv = conv(in_channels, out_channels, stride, kernel=5, bias=True)
>        else:
>            self.new_conv = conv(in_channels, out_channels, stride, kernel=7, bias=True)

in ResNet post fold file.
Could you please tell me how to set the kernel size properly as which was set to 5 and 7 in your code.
Also, the code of calculate new kernel seems difficult for me to understand, I would appreciate it if you could explain in a detailed way.
Thanks in adv!

**Comment by LayerFolding** [comment]
While combining 2 kernels with the size of 3x3, the new kernel has a size of 5x5.
But, in the same case, if the stride is equal to 2, the receptive field had grown, and then the new kernel must have the shape of 7x7.
