### ISSUE TITLE
How to define dim.

### ISSUE THREAD

**Issue by mino1710605** [LayerFolding/Layer-Folding#4]
Hi,

I have read your paper and code recently, while the result and idea in tis paper seems amazing.
However, due to inefficiency in knowledge, I was confused when I saw the follow code (line 204 of ResNet_Cifar10_postfold.py & line 193 of VGG_Cifar10_postfold.py):

```
    # calculate the new kernels
    index = 0
    dim = 13
```
in ResNet postfold file.

```
     for idx, m in enumerate(model.features):
         if isinstance(m, nn.PReLU) and idx + 2 <= len(model.features):
            if isinstance(model.features[idx - 3], nn.MaxPool2d) and m.weight == 1:
                in_c = model.features[idx - 2].in_channels
                out_c = model.features[idx - 2].out_channels
                dim = 21
```
in VGG postfold file.

Could you please tell me how to define dim.
I would appreciate it if you could explain in a detailed way.
Thanks in adv!

**Comment by LayerFolding** [comment]
Hi,
It doesn't matter too much. Having a sufficiently high dimension is important
